terminate called recursively
terminate called recursively
terminate called after throwing an instance of 'std::system_error'
terminate called recursively
bash: line 7:  5181 Aborted                 (core dumped) ./a.out
