2
3
terminate called after throwing an instance of 'std::runtime_error'
  what():  No such element found
bash: line 10: 10001 Aborted                 (core dumped) ./a.out 5 8 9 2 0 1 3 4 7
