terminate called after throwing an instance of 'std::runtime_error'
  what():  fuck you
bash: line 7: 10251 Aborted                 (core dumped) ./a.out
